// Pre-loaded universal societal-challenge demos. Matches auto-generated by the engine.
import { runAIAnalysis, matchUniversities, matchIndustries, LIFECYCLE } from "./engine";

const RAW = [
  {
    id: "jmib-demo-water-001",
    title: "Water logging near school road every monsoon",
    description:
      "Every monsoon, water logging occurs on the approach road to the government school, making it unusable for children and residents. Poor storm-water drainage causes stagnation, safety hazards and missed school days.",
    domain: "Water & Sanitation",
    district: "Ranchi",
    peopleAffected: "12,000+ residents & students",
    urgency: "High",
    evidence: "Ward-level monsoon flooding reports; local school attendance records",
    impactScore: 88,
    featured: true,
    stageIndex: 4,
    createdAt: "2026-05-20T09:00:00.000Z",
  },
  {
    id: "jmib-demo-light-002",
    title: "Broken streetlights around school zone",
    description:
      "Multiple streetlights near the residential school zone have been non-functional for months, raising safety concerns for students and women commuting after dusk. There is no easy way to report and track repairs.",
    domain: "Electricity & Street Lighting",
    district: "Dhanbad",
    peopleAffected: "8,500+ residents",
    urgency: "Moderate",
    evidence: "Resident welfare association complaints; night safety survey",
    impactScore: 74,
    stageIndex: 2,
    createdAt: "2026-05-24T11:30:00.000Z",
  },
  {
    id: "jmib-demo-health-003",
    title: "Affordable anemia screening for pregnant women",
    description:
      "Anemia affects a large share of pregnant women in rural blocks, yet blood-based screening needs lab access most PHCs lack. A low-cost, non-invasive point-of-care hemoglobin screening tool is urgently needed for ASHA/ANM workers.",
    domain: "Health & Healthcare",
    district: "Gumla",
    peopleAffected: "340,000+ pregnant women",
    urgency: "High",
    evidence: "NFHS-5 district health data; district maternal health survey 2024",
    impactScore: 92,
    stageIndex: 5,
    createdAt: "2026-05-12T09:00:00.000Z",
  },
  {
    id: "jmib-demo-agri-004",
    title: "Farm irrigation monitoring for smallholders",
    description:
      "Smallholder farmers lack reliable data on soil moisture and water availability, leading to over- or under-irrigation and crop loss. Affordable sensor-based irrigation advisory could improve yields and conserve water.",
    domain: "Agriculture & Rural Development",
    district: "Hazaribagh",
    peopleAffected: "5,000+ farmers",
    urgency: "High",
    evidence: "Block agriculture office yield data; farmer group interviews",
    impactScore: 86,
    stageIndex: 10,
    createdAt: "2026-05-08T08:15:00.000Z",
  },
  {
    id: "jmib-demo-waste-005",
    title: "Waste segregation in urban wards",
    description:
      "Mixed household waste is dumped without segregation, overloading landfills and causing pollution. The city needs a source-segregation system with decentralized processing and citizen participation.",
    domain: "Environment & Waste Management",
    district: "Jamshedpur",
    peopleAffected: "220,000+ households",
    urgency: "Moderate",
    evidence: "Municipal solid-waste audit 2025",
    impactScore: 79,
    stageIndex: 9,
    createdAt: "2026-04-29T10:00:00.000Z",
  },
  {
    id: "jmib-demo-tele-006",
    title: "Rural telemedicine access in tribal blocks",
    description:
      "Remote tribal blocks have limited specialist access and unreliable connectivity. An offline-first tele-consultation setup that syncs when connectivity returns could bridge the specialist gap.",
    domain: "Health & Healthcare",
    district: "Dumka",
    peopleAffected: "120,000+ residents",
    urgency: "Moderate",
    evidence: "District connectivity and PHC staffing audit 2025",
    impactScore: 78,
    stageIndex: 1,
    createdAt: "2026-05-22T11:30:00.000Z",
  },
  {
    id: "jmib-demo-access-007",
    title: "Accessibility gaps at public buildings",
    description:
      "Several public offices and health centers lack ramps, accessible toilets and signage, excluding persons with disabilities and the elderly. A phased accessibility upgrade with an audit is needed.",
    domain: "Accessibility & Disability",
    district: "Ranchi",
    peopleAffected: "40,000+ persons with disabilities",
    urgency: "Moderate",
    evidence: "Disability rights group accessibility audit",
    impactScore: 71,
    stageIndex: 2,
    createdAt: "2026-05-15T14:00:00.000Z",
  },
  {
    id: "jmib-demo-edu-008",
    title: "School dropout and learning access in rural blocks",
    description:
      "High dropout rates and low learning outcomes persist in rural upper-primary schools due to limited resources and no early-warning for at-risk students. A blended learning and retention program is needed.",
    domain: "Education",
    district: "Palamu",
    peopleAffected: "18,000+ students",
    urgency: "High",
    evidence: "District education dashboard; dropout tracking data",
    impactScore: 83,
    stageIndex: 4,
    createdAt: "2026-05-05T09:30:00.000Z",
  },
];

export const SEED_CHALLENGES = RAW.map((c) => {
  const ai = runAIAnalysis(c);
  if (c.impactScore) ai.impactScore = c.impactScore;
  return {
    ...c,
    status: LIFECYCLE[c.stageIndex] || "Submitted",
    ai,
    universities: matchUniversities(c),
    industries: matchIndustries(c),
  };
});
